
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SLASH DOCUMENTCLASS BEGIN END ARTICLE DOCUMENT TITLE AUTHOR DATE LBRACE RBRACE TEXTrootstatement : DOCUMENTCLASS LBRACE ARTICLE RBRACE body\n    optionaltags : TITLE LBRACE oneormoretext RBRACE\n                 | DATE LBRACE oneormoretext RBRACE\n                 | AUTHOR LBRACE oneormoretext RBRACE\n    body : optionaltags body\n            | SLASH BEGIN LBRACE DOCUMENT RBRACE oneormoretext SLASH END LBRACE DOCUMENT RBRACEoneormoretext : oneormoretext TEXT \n                     | TEXT  empty :'
    
_lr_action_items = {'BEGIN':([8,],[13,]),'LBRACE':([2,7,9,11,13,30,],[3,12,14,16,19,31,]),'END':([29,],[30,]),'RBRACE':([4,17,18,20,21,22,24,32,],[5,-8,23,25,26,-7,27,33,]),'AUTHOR':([5,10,23,25,26,],[11,11,-2,-3,-4,]),'TEXT':([12,14,16,17,18,20,21,22,27,28,],[17,17,17,-8,22,22,22,-7,17,22,]),'TITLE':([5,10,23,25,26,],[7,7,-2,-3,-4,]),'DOCUMENTCLASS':([0,],[2,]),'SLASH':([5,10,17,22,23,25,26,28,],[8,8,-8,-7,-2,-3,-4,29,]),'DATE':([5,10,23,25,26,],[9,9,-2,-3,-4,]),'ARTICLE':([3,],[4,]),'DOCUMENT':([19,31,],[24,32,]),'$end':([1,6,15,33,],[0,-1,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([5,10,],[6,15,]),'rootstatement':([0,],[1,]),'optionaltags':([5,10,],[10,10,]),'oneormoretext':([12,14,16,27,],[18,20,21,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rootstatement","S'",1,None,None,None),
  ('rootstatement -> DOCUMENTCLASS LBRACE ARTICLE RBRACE body','rootstatement',5,'p_rootstatement_terminal','parser.py',12),
  ('optionaltags -> TITLE LBRACE oneormoretext RBRACE','optionaltags',4,'p_optionaltags_terminal','parser.py',21),
  ('optionaltags -> DATE LBRACE oneormoretext RBRACE','optionaltags',4,'p_optionaltags_terminal','parser.py',22),
  ('optionaltags -> AUTHOR LBRACE oneormoretext RBRACE','optionaltags',4,'p_optionaltags_terminal','parser.py',23),
  ('body -> optionaltags body','body',2,'p_body_terminal','parser.py',33),
  ('body -> SLASH BEGIN LBRACE DOCUMENT RBRACE oneormoretext SLASH END LBRACE DOCUMENT RBRACE','body',11,'p_body_terminal','parser.py',34),
  ('oneormoretext -> oneormoretext TEXT','oneormoretext',2,'p_oneormoretext_terminal','parser.py',42),
  ('oneormoretext -> TEXT','oneormoretext',1,'p_oneormoretext_terminal','parser.py',43),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',51),
]
